app/(stack)/index.tsx
app/(stack)/register.tsx
components/CustomDropdown.tsx
components/LanguageSelect.tsx
styles/theme.ts

- Added consistent gap spacing for form sections
- Simplified icon and input styling
- Removed redundant margin styles
- Updated CustomDropdown and LanguageSelect components
- Added primaryLight color variant in theme

fix: set language warning

---

components/NewTranslationModal.tsx

- Separate audio attachment processing from translation creation
- Ensure audio attachment is optional when creating a translation
- Simplify translation submission logic

refactor: Improve audio attachment handling in translation creation

---

app/(stack)/projects/[projectId]/quests/[questId]/assets/index.tsx
app/(stack)/projects/[projectId]/quests/index.tsx
app/(stack)/projects/index.tsx
components/ProjectDetails.tsx
components/QuestDetails.tsx

I hid the stats behind a button and fixed up the back button overlap problem

61 enhance the project stats should not popup every time

---

.gitignore
app/(stack)/profile.tsx
app/(stack)/projects/[projectId]/quests/[questId]/assets/[assetId].tsx
app/(stack)/register.tsx
app/_layout.tsx
database_services/userService.tsx
db/drizzleSchema.ts
drizzle/0003_lethal_living_mummy.sql
drizzle/meta/0003_snapshot.json
drizzle/meta/_journal.json
drizzle/migrations.js
guards/TermsGuard.tsx
package.json
services/translations.ts

Would appreciate review on the TermsGuard I added (which should block using the app and/or syncing if you haven't accepted the terms).

37 feature add terms conditions to registration process

---

app/(stack)/register.tsx
components/TermsModal.tsx
database_services/userService.tsx
drizzle/relations.ts
drizzle/schema.ts
guards/TermsGuard.tsx

This commit was missed on the previous PR - had it locally but never hit push.

Abstract terms and conditions modal

---

app/(stack)/projects/[projectId]/quests/[questId]/assets/index.tsx

So, basically, the issue was the DB query just returned whatever order they were added to the DB with (or whatever was default). What I am doing here is tokenizing the asset name and trying to sort alphabetically AND numerically depending on the extracted token components of the name. It should be fairly robust and default to alphabetical or numeric in cases where it's not a verse reference. It should also work with any Codex cell ids we wind up importing.
See properly ordered assets below. This should not interfere with custom sorting/filtering the user selects.
----
- Implement sophisticated sorting algorithm for assets based on numeric references in names and tags
- Add default sorting mechanism that prioritizes numeric references (e.g., chapter and verse)
- Improve sorting logic to …

feat: Enhance asset sorting with advanced numeric reference extraction

---

app/(stack)/projects/index.tsx

This pr simplifies project filtering and saves the last filter option to the users device. It also fixes the issue with target and source not showing the correct lists

74 user needs to a simple way to filter project

---

app.config.ts
components/NewTranslationModal.tsx
db/supabase/SupabaseStorageAdapter.ts

- Updated audio attachment variable from ID to filename in NewTranslationModal component.
- Removed unused Android build properties from app.config.ts.
- Added directory existence check before writing files in SupabaseStorageAdapter.

fix: attachment upload + folder support

---

app.config.ts
app/(stack)/projects/index.tsx
components/NewTranslationModal.tsx
db/powersync/AttachmentQueue.ts
db/supabase/SupabaseStorageAdapter.ts
styles/theme.ts

- Updated app name from 'langquest' to 'LangQuest' in app.config.ts.
- Wrapped project card title and language text in a View for better layout in projects/index.tsx.
- Enhanced NewTranslationModal with KeyboardAvoidingView for improved user experience and adjusted audio attachment handling.
- Simplified attachment record creation in AttachmentQueue by separating filename and local URI.
- Removed unnecessary directory creation in SupabaseStorageAdapter when writing files.
- Updated shared styles for card components to improve layout consistency.

fix: translation upload

---

components/AudioPlayer.tsx
components/AudioRecorder.tsx
components/NewTranslationModal.tsx

... checkbox for longer recording time
- Updated AudioPlayer to handle playback status updates asynchronously and improved sound loading logic.
- Refactored AudioRecorder to include maximum recording duration calculation based on selected quality, added warning for nearing limits, and improved cleanup on unmount.
- Integrated resetRecording prop in NewTranslationModal to clear audio URI after recording completion.

fix: correct audio player logic + max recording duration + ios low quality

---

app/(stack)/notifications.tsx
components/AudioRecorder.tsx
components/Drawer.tsx
services/translations.ts

…ion page
- Added useTranslation hook to Notifications and AudioRecorder components for localization.
- Updated notifications title to use translated text.
- Enhanced audio recorder to display remaining time in the selected language.
- Added 'remaining' translation to the translations service.

feat: add translation for remaining recording time + hide notification page

---

.github/workflows/deploy-sync-rules.yml

- Changed the deployment command in deploy-sync-rules.yml from 'powersync' to 'npx powersync' for improved execution context.

fix: update command for deploying sync rules in workflow

---

.github/workflows/preview.yml

- Introduced a new GitHub Actions workflow to automate EAS updates on the 'dev' branch.
- The workflow includes steps for environment setup, fetching Supabase branch info, and creating a preview.
- Added logic to rename the .env.local file and update the Supabase URL in the .env file based on the current branch.

feat: add preview workflow for EAS updates

---

.gitignore
supabase/.env.preview
supabase/config.toml
supabase/templates/email_change.html
supabase/templates/reset_password.html

- Added a new .env.preview file for environment variable management.
- Updated site URL and additional redirect URLs in config.toml for production readiness.
- Enabled SMTP settings for email notifications using Resend.
- Created email templates for account confirmation and password reset in multiple languages.

feat: update Supabase configuration and email templates

---

app/request-reset-password.tsx

- Modified the redirect URL in the password reset function to append the app variant as a query parameter when not in production, ensuring proper handling of different environments.

fix: update password reset redirect URL to include environment variant

---

app/_layout.tsx
app/register.tsx
app/request-reset-password.tsx
app/sign-in.tsx
app/terms.tsx
contexts/LanguageContext.tsx
hooks/useTranslation.ts

TLDR: using language context now so unauthenticated pages automatically pull in the UI language set at the layout level.
- Added LanguageContext to manage the current language state across the application.
- Integrated LanguageProvider in the RootLayout to provide language context to child components.
- Updated components (Register, SignIn, Terms, RequestResetPassword) to utilize the new language context for language selection and translation.
- Refactored language handling logic to streamline language selection and storage in AsyncStorage.

feat: implement LanguageContext for improved language management

---

package.json
supabase/functions/send-email/index.ts

- Added separate deployment scripts for the send-email function in development and production environments in `package.json`.
- Updated the send-email function to support new email handling logic, allowing for the use of a new email address if provided.
- Refactored language selection logic to utilize `ui_language_id` for improved localization support.

feat: enhance send-email function (fix sign up language)

---

supabase/functions/send-email/index.ts

- Removed unnecessary console log statements related to user and profile language IDs in the send-email function for improved readability and performance.

refactor: clean up logging in send-email function

---

supabase/functions/send-email/index.ts

- Added support for plain text email rendering alongside HTML for 'signup' and 'recovery' actions.
- Refactored email component creation for improved readability and maintainability.

feat: enhance email rendering in send-email function

---

app/(drawer)/(stack)/projects/[projectId]/quests/[questId]/assets/index.tsx
app/(drawer)/(stack)/projects/[projectId]/quests/index.tsx
utils/sortingUtils.ts

- Separated default asset sorting logic, applied to quest cards as well

Sorting algorithm applies to quests

---

README.md
app.config.ts
app/(root)/(drawer)/_layout.tsx
app/_layout.tsx
contexts/AuthContext.tsx
contexts/PostHogProvider.tsx
db/supabase/SupabaseConnector.ts
package-lock.json
package.json
utils/supabaseUtils.ts

- Updated app.config.ts to dynamically set app name, slug, and unique identifier based on the environment (development, preview, production).
- Added expo-screen-orientation dependency to manage screen orientation settings.
- Refactored imports in various files for consistency and clarity.
- Updated README to clarify Docker Desktop requirements.

feat: enhance app configuration and add screen orientation support

---

app.config.ts
package.json
supabase/config.toml

- Added siteUrl variable in app.config.ts to dynamically set URL for deep linking.
- Updated deep link configurations to use siteUrl for reset-password and registration-confirmation paths.
- Changed Supabase function project reference in package.json and config.toml to the new project ID.

chore: update app configuration and Supabase function references

---

app/(root)/_layout.tsx
contexts/AuthContext.tsx

- Added a console log for redirecting to terms if not accepted.
- Updated auth state change handler to reset current user on anonymous session sign-in and refined condition to check for non-anonymous users.

fix: improve terms acceptance handling and enhance auth state management

---

README.md
components/AssetFilterModal.tsx
components/QuestFilterModal.tsx

- Updated the README to clarify the command for obtaining the .env file.
- Added a remove button in AssetFilterModal and QuestFilterModal to allow users to clear sorting options.

feat: add remove button in filter modals

---

app/_layout.tsx
components/AudioPlayer.tsx
components/Carousel.tsx
components/MiniAudioPlayer.tsx
components/NewTranslationModal.tsx
components/TranslationModal.tsx
contexts/AudioContext.tsx

- Added AudioProvider to manage audio playback state and functionality.
- Refactored AudioPlayer and MiniAudioPlayer components to utilize the new audio context.
- Updated layout to include AudioProvider, ensuring audio context is available throughout the app.
- Enhanced modal components to stop audio playback when closed.

feat: integrate audio context for improved audio management

---

components/AssetFilterModal.tsx
components/QuestFilterModal.tsx

- Updated AssetFilterModal and QuestFilterModal to sort options numerically when applicable, falling back to alphabetical sorting for non-numeric values.

feat: enhance sorting in filter modals

---

supabase/functions/send-email/index.ts

- Added rate limiting functionality to the email sending service to prevent abuse.
- Integrated Upstash Redis for managing rate limits with a fixed window of 4 requests per hour.
- Updated imports to include necessary libraries for Redis and rate limiting.

feat: implement rate limiting for email sending

---

app/(root)/(drawer)/_layout.tsx
contexts/AuthContext.tsx

…hContext
- Moved the authentication check in AuthLayout to ensure redirection to sign-in occurs correctly.
- Improved logging in AuthContext to include user email and anonymity status during authentication state changes.

fix: keep getting logged out

---

app.config.ts
app/_layout.tsx
components/UpdateBanner.tsx
hooks/useExpoUpdates.ts
package-lock.json
package.json

Please look over - unable to fully test until it's on the play store

Added OTA update banner, dev preview mode

---

components/AssetFilterModal.tsx
components/QuestFilterModal.tsx
components/questsComponents/QuestList.tsx
db/drizzleSchema.ts
db/powersync/system.ts
hooks/db/useAssets.ts
hooks/db/useQuests.ts
hooks/db/useTags.ts
hooks/db/useTranslations.ts
hooks/db/useVotes.ts
hooks/useHybridSupabaseQuery.ts
supabase/migrations/20250710143002_add_tag_category_views.sql
views/AssetsView.tsx
views/QuestsView.tsx

…data fetching
- Updated AssetFilterModal and QuestFilterModal to fetch tag categories and assets directly from the server, improving performance and reducing client-side filtering logic.
- Introduced infinite loading for tags in both modals, allowing for better scalability with large datasets.
- Removed redundant client-side filtering functions, as filtering is now handled server-side.
- Enhanced the use of hooks for fetching tags and assets, ensuring a more streamlined data management process.
This refactor aims to optimize the user experience by leveraging server capabilities for data handling.

feat: search bar

---

README.md
components/AppDrawer.tsx
contexts/AuthContext.tsx
db/powersync/system.ts
hooks/useLocalization.ts
utils/backupUtils.ts
utils/restoreUtils.ts

- Fixed {count} to use actual number in alert ("backed up 2 audio files")
- Re-enabled backup/restore buttons when device is offline
- No longer duplicating backup files
- Instructions in readme to run app on phone with logging while offline

Fix file backup

---

navigators/AuthNavigator.tsx
utils/sharedUtils.ts
views/ForgotPasswordView2.tsx
views/RegisterView2.tsx
views/ResetPasswordView2.tsx
views/SignInView2.tsx

Added link to navigate to Register page when user put invalid credentials on Sign-In. 
Added navigation feature to keep email already provided among all Authentication view. 
Added function to prevent flickering after navigate to next page.

Fixing redirect link when invalid credentials

---

supabase/migrations/20250813000001_replace_jan_28_migration_deep_clone.sql

Should fix migration issue with merging into dev

Create migration to replace predated deep clone

---

app.config.ts
package-lock.json
package.json

Reverts genesis-ai-dev/langquest#351

Revert "Remove static output configuration from app.config.ts and update tail…"

---

.gitignore
supabase/migrations/20250916123000_update_creator_id_fk_actions.sql
views/SignInView2.tsx

- password field on sign in (2) file adjusted to not capitalize
- cascading in db adjusted to set creator id to null on project, quest, asset records when creator is deleted (rather than preventing deletion)

password input, db cascades modified
